mutation CreateUser {
  createUser(
    createUser: {
      firstName: "Jose"
      lastName: "Estrella"
      email: "jose@avg.com"
      password: "password"
    }
  ) {
    _id
    firstName
    email
    password
    createdAt
    roles
  }
}

query Login {
  login(email: "jose@avg.com", password: "password")
}


# must add an "HTTP HEADER" with auth token
# 
# {
#   "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2VAYXZnLmNvbSIsIl9pZCI6IjYyNjQ5NDkzMmJhNmEwOTJkNWVmMjEwMCIsImlhdCI6MTY1MDc3NDM1NSwiZXhwIjoxNjUwODYwNzU1fQ.d0kfS1xmt2IiSBFPFKUp1lde8-XvkIaiE_SWcO7esbw"
# }



query FindOne {
  findOne(_id: "615cf51fde81562fe6247590") {
    _id
    firstName
    lastName
    email
  }
}

query getAllUsers {
  getAllUsers {
    _id
    firstName
    lastName
    email
  }
}


mutation UpdatePassword {
  updateUserPassword(currentPassword: "sssss", newPassword: "aaaaa") {
    firstName
  }
}

mutation UpdateUser {
  updateUser(updateUser: { email: "test@me.com", firstName: "Steve" }) {
    _id
    firstName
    lastName
    email
  }
}
